version: "3.5"

services:
  serviceone:
    build:
      context: ./service1
      dockerfile: Dockerfile
    container_name: serviceone
    environment:
      NODE_ENV: docker
    working_dir: /app
    ports:
      - 80:80
  servicetwo:
    build:
      context: ./service2
      dockerfile: Dockerfile
    container_name: servicetwo
    environment:
      NODE_ENV: docker
    working_dir: /app
    ports:
      - 8080:8080
